# Generated by Django 4.2.5 on 2023-12-22 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerRegistration',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_firstname', models.CharField(max_length=255)),
                ('user_lastname', models.CharField(max_length=255)),
                ('user_address', models.TextField(max_length=255)),
                ('user_mobile_no', models.CharField(max_length=12, unique=True)),
                ('user_emailid', models.CharField(max_length=255, unique=True)),
                ('user_password', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'BuyerRegistration_table',
            },
        ),
    ]
