# Generated by Django 4.2.2 on 2024-01-10 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerpurchase',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.product'),
        ),
        migrations.AddField(
            model_name='buyerpayment',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.buyerregistration'),
        ),
        migrations.AddField(
            model_name='buyerpayment',
            name='details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.buyerpurchase'),
        ),
        migrations.AddField(
            model_name='buyerfeedback',
            name='feedback_login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.buyerregistration'),
        ),
        migrations.AddField(
            model_name='buyerfeedback',
            name='feedback_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.product'),
        ),
        migrations.AddField(
            model_name='buyercart',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.buyerregistration'),
        ),
        migrations.AddField(
            model_name='buyercart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.product'),
        ),
        migrations.AddField(
            model_name='buyer_checkout_details',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.buyerregistration'),
        ),
    ]
