# Generated by Django 4.2.2 on 2024-01-08 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller', '0001_initial'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerfeedback',
            name='feedback_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.product'),
        ),
        migrations.AddField(
            model_name='buyercart',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.buyerregistration'),
        ),
        migrations.AddField(
            model_name='buyercart',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.product'),
        ),
    ]
