<<<<<<< HEAD
# Generated by Django 4.2.5 on 2024-01-09 10:15
=======
# Generated by Django 4.2.2 on 2024-01-09 04:38
>>>>>>> 0d8cd30df35de66cc409016e0b4ae856395dde01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller', '0001_initial'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
<<<<<<< HEAD
            model_name='buyerpurchase',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.product'),
        ),
        migrations.AddField(
            model_name='buyerpayment',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.buyerregistration'),
        ),
        migrations.AddField(
            model_name='buyerpayment',
            name='details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.buyerpurchase'),
        ),
        migrations.AddField(
            model_name='buyerfeedback',
            name='feedback_login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.buyerregistration'),
        ),
        migrations.AddField(
            model_name='buyerfeedback',
            name='feedback_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.product'),
        ),
        migrations.AddField(
            model_name='buyercart',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.buyerregistration'),
        ),
        migrations.AddField(
            model_name='buyercart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.product'),
=======
            model_name='buyercart',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.product'),
>>>>>>> 0d8cd30df35de66cc409016e0b4ae856395dde01
        ),
    ]
