# Generated by Django 4.2.2 on 2023-12-26 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_buyercart_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=100)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.buyerregistration')),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.checkout_details')),
            ],
        ),
    ]
