# Generated by Django 4.2.2 on 2024-01-10 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyerpayment',
            name='order',
        ),
    ]
