# Generated by Django 4.2.5 on 2024-01-10 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
        ('base', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Checkout_details',
            new_name='BuyerCheckout_details',
        ),
        migrations.RenameModel(
            old_name='Return',
            new_name='BuyerReturn',
        ),
    ]
