# Generated by Django 4.2.5 on 2024-01-03 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerpayment',
            name='buyer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.buyerregistration'),
        ),
        migrations.AlterField(
            model_name='buyerpayment',
            name='details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.buyerpurchase'),
        ),
    ]
