# Generated by Django 4.2.2 on 2024-01-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_buyerpayment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerpayment',
            name='order_key',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
