# Generated by Django 4.2.2 on 2023-12-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerregistration',
            name='user_photo',
            field=models.FileField(default='defult.jpg', null=True, upload_to='buyer/'),
        ),
    ]
