# Generated by Django 4.2.5 on 2024-01-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_buyerregistration_user_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerregistration',
            name='user_mobile_no',
            field=models.CharField(default=None, max_length=12, null=True, unique=True),
        ),
    ]
