# Generated by Django 4.2.2 on 2023-12-26 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_buyerregistration_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout_details',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
