# Generated by Django 4.2.5 on 2023-12-25 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_buyerregistration_user_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=100)),
                ('apartment_address', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('address_type', models.CharField(choices=[('State Name', 'Andhra Pradesh'), ('State Name', 'Arunachal Pradesh'), ('State Name', 'Assam')], max_length=20)),
                ('ord_rec_name', models.CharField(max_length=255)),
                ('ord_rec_mobile_no', models.CharField(max_length=12)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.AlterField(
            model_name='buyerregistration',
            name='user_photo',
            field=models.FileField(default='defult.jpg', null=True, upload_to='media/'),
        ),
    ]
