# Generated by Django 4.2.5 on 2024-01-05 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_buyerregistration_user_mobile_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.buyerpayment')),
            ],
        ),
    ]
