# Generated by Django 4.2.2 on 2023-12-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_checkout_details_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyercart',
            name='product_color',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
