# Generated by Django 4.2.5 on 2024-01-05 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_buyerorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyerorder',
            name='is_confirmed',
        ),
    ]
