# Generated by Django 4.2.5 on 2023-12-25 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_address_address_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address_type',
            new_name='select_state',
        ),
    ]
