# Generated by Django 4.2.5 on 2024-01-05 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_buyerorder_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerorder',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.buyerregistration'),
        ),
    ]
