# Generated by Django 4.2.5 on 2024-01-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_buyerorder_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerpayment',
            name='cancel',
            field=models.BooleanField(default=True),
        ),
    ]
