# Generated by Django 4.2.2 on 2023-12-28 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_return'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return',
            name='product',
        ),
    ]
