# Generated by Django 4.2.2 on 2023-12-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_return_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='order_return_image',
            field=models.FileField(default='default.jpg', null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='return',
            name='order_return_message',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
