# Generated by Django 4.2.5 on 2024-01-06 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_buyerpayment_cancel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
