# Generated by Django 4.2.5 on 2024-01-07 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_return_return_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='buyercart',
            table='Buyer_Cart',
        ),
        migrations.AlterModelTable(
            name='buyerfeedback',
            table='Buyer_feedback',
        ),
        migrations.AlterModelTable(
            name='buyerpayment',
            table='Buyer_Payment',
        ),
        migrations.AlterModelTable(
            name='buyerpurchase',
            table='Buyer_Purchase',
        ),
        migrations.AlterModelTable(
            name='buyerregistration',
            table='Buyer_Registration',
        ),
        migrations.AlterModelTable(
            name='checkout_details',
            table='Buyer_Checkout_details',
        ),
        migrations.AlterModelTable(
            name='return',
            table='Buyer_Return',
        ),
    ]
