# Generated by Django 4.2.5 on 2023-12-25 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_buyeraddress_id_buyeraddress_address_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyeraddress',
            options={},
        ),
        migrations.AlterModelTable(
            name='buyeraddress',
            table='Addresses',
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('total', models.IntegerField(default=0)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.buyerregistration')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.buyeraddress')),
            ],
        ),
    ]
