# Generated by Django 4.2.2 on 2023-12-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_return_order_return_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='return_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='return',
            name='return_shipping_Fee',
            field=models.IntegerField(default=0),
        ),
    ]
