# Generated by Django 4.2.2 on 2023-12-28 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_return_return_date_return_return_shipping_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return',
            name='order_return_image',
        ),
    ]
