# Generated by Django 4.2.5 on 2023-12-25 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_buyeraddress_options_alter_buyeraddress_table_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='BuyerCart',
        ),
        migrations.AlterModelTable(
            name='buyeraddress',
            table='BuyerAddresses_table',
        ),
        migrations.AlterModelTable(
            name='buyercart',
            table='BuyerBuyerCart_table',
        ),
    ]
