# Generated by Django 4.2.2 on 2023-12-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_return_order_return_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='order_return_message',
            field=models.CharField(max_length=100, null='N/A'),
        ),
    ]
