# Generated by Django 4.2.5 on 2023-12-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rename_cart_buyercart_alter_buyeraddress_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyercart',
            name='product_size',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='buyercart',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
