# Generated by Django 4.2.2 on 2024-01-03 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0008_product_product'),
        ('base', '0013_alter_return_order_return_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerFeedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_description', models.TextField(max_length=500)),
                ('feedback_datetime', models.DateTimeField(auto_now_add=True)),
                ('feedback_rating', models.IntegerField()),
                ('feedback_photo', models.FileField(null=True, upload_to='buyer/')),
                ('feedback_login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.buyerregistration')),
                ('feedback_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.product')),
            ],
        ),
    ]
