# Generated by Django 4.2.2 on 2023-12-22 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.FileField(default='default.jpg', upload_to='media/')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_no', models.CharField(default=0, max_length=10, unique=True)),
                ('address', models.TextField()),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_images', models.JSONField()),
                ('SKU', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.IntegerField()),
                ('product_sale_price', models.IntegerField()),
                ('product_quantity', models.IntegerField()),
                ('product_category', models.CharField(choices=[('CLOTHE', 'CLOTHE'), ('ELECTRONICS', 'ELECTRONICS'), ('BOOKS', 'BOOKS'), ('BEAUTY', 'BEAUTY'), ('MEN ACCESSORIES', 'MEN ACCESSORIES'), ('WOMEN ACCESSORIES', 'WOMEN ACCESSORIES'), ('FURNITURE', 'FURNITURE'), ('GARDEN', 'GARDEN')], max_length=50)),
                ('product_items', models.CharField(choices=[('CLOTHE', (('BOY', 'BOY'), ('GIRL', 'GIRL'), ('MEN', 'MEN'), ('WOMEN', 'WOMEN'))), ('ELECTRONICS', (('MOBILE', 'MOBILE'), ('LAPTOP', 'LAPTOP'), ('TABLET', 'TABLET'), ('COMPUTER', 'COMPUTER'), ('TV', 'TV'), ('CAMERA', 'CAMERA'), ('HOME AUDIO', 'HOME AUDIO'))), ('BOOKS', (('FINANCE & ACCOUNTING EXAMS BOOKS', 'FINANCE & ACCOUNTING EXAMS BOOKS'), ('GOVERNMENT EXAMS BOOKS', 'GOVERNMENT EXAMS BOOKS'), ('EXAMS BY UPSC BOOKS', 'EXAMS BY UPSC BOOKS'), ('ENGINEERING ENTRANCE BOOKS', 'ENGINEERING ENTRANCE BOOKS'), ('DEFENCE BOOKS', 'DEFENCE BOOKS'), ('BANKING & INSURANCE BOOKS', 'BANKING & INSURANCE BOOKS'), ('ARTS, DESIGN AND EDUCATION BOOKS', 'ARTS, DESIGN AND EDUCATION BOOKS'))), ('BEAUTY', (('MAKEUP', 'MAKEUP'), ('SKIN', 'SKIN'), ('HAIR', 'HAIR'), ('FRAGRANCES', 'FRAGRANCES'), ('MENS GROOMING', 'MENS GROOMING'), ('UNISEX PERSONAL CARE', 'UNISEX PERSONAL CARE'))), ('MEN ACCESSORIES', (('BELT', 'BELT'), ('CAPS & HATS', 'CAPS & HATS'), ('MUFFLERS, SCARVES & GLOVES', 'MUFFLERS, SCARVES & GLOVES'), ('HANDKERCHIEFS', 'HANDKERCHIEFS'), ('SOCKS', 'SOCKS'), ('SUNGLASSES', 'SUNGLASSES'), ('WALLET', 'WALLET'), ('WATCHES', 'WATCHES'), ('HELMET', 'HELMET'))), ('WOMEN ACCESSORIES', (('JEWELLERY', 'JEWELLERY'), ('BELTS', 'BELTS'), ('CAPS & HATS', 'CAPS & HATS'), ('HAIR ACCESSORIES', 'HAIR ACCESSORIES'), ('SOCKS', 'SOCKS'), ('SUNGLASSES', 'SUNGLASSES'), ('UMBRELLAS', 'UMBRELLAS'), ('WATCHES', 'WATCHES'), ('PINS', 'PINS'))), ('FURNITURE', 'FURNITURE'), ('GARDEN', (('WATERING CANS', 'WATERING CANS'), ('GARDENING TOOLS', 'GARDENING TOOLS'), ('HOSE NOZZLES', 'HOSE NOZZLES'), ('GARDEN FAUCETS', 'GARDEN FAUCETS'), ('WATER PUMPS', 'WATER PUMPS'), ('GARDEN SPRAY', 'GARDEN SPRAY')))], max_length=50)),
                ('product_branding', models.CharField(max_length=50)),
                ('product_tags', models.CharField(max_length=50)),
                ('product_size', models.CharField(max_length=50)),
                ('product_color', models.CharField(max_length=50)),
                ('product_fabric', models.CharField(max_length=50)),
                ('product_description', models.TextField()),
                ('product_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.register')),
            ],
        ),
    ]
