# Generated by Django 4.2.2 on 2023-12-26 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('product_color', models.CharField(max_length=50, null=True)),
                ('product_size', models.CharField(max_length=50, null=True)),
                ('status', models.BooleanField(default=True)),
                ('total', models.IntegerField(default=0)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.buyer')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.product')),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=200)),
                ('second_address', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=25)),
                ('postcode', models.IntegerField(default=0)),
                ('phone', models.CharField(max_length=124)),
                ('email', models.CharField(max_length=50)),
                ('order', models.CharField(max_length=100, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.buyer')),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.cart')),
            ],
        ),
        migrations.AlterField(
            model_name='accept',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.buyer'),
        ),
        migrations.AlterField(
            model_name='cancel',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.buyer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.buyer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.cart'),
        ),
    ]
