# Generated by Django 4.2.2 on 2024-01-10 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_buyerpayment_order'),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.buyerpayment'),
        ),
    ]
