# Generated by Django 4.2.2 on 2023-12-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='mobile_no',
            field=models.CharField(default='+ 91', max_length=10, unique=True),
        ),
    ]
