# Generated by Django 4.2.2 on 2024-01-10 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_alter_order_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='details',
            new_name='payment',
        ),
    ]
