# Generated by Django 4.2.2 on 2023-12-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_buyer_details_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='company_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='dispatch_date',
            field=models.DateField(null=True),
        ),
    ]
