# Generated by Django 4.2.2 on 2023-12-26 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_remove_cart_buyer_remove_cart_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cart',
            new_name='details',
        ),
    ]
