# Generated by Django 4.2.2 on 2023-12-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_details_company_id_details_dispatch_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='order_date',
            field=models.DateField(null=True),
        ),
    ]
