# Generated by Django 4.2.2 on 2023-12-26 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_rename_cart_order_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Barcode',
        ),
    ]
