# Generated by Django 4.2.2 on 2023-12-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_details_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='dispatch_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='order_date',
            field=models.DateTimeField(null=True),
        ),
    ]
