# Generated by Django 4.2.2 on 2023-12-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_delete_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_date',
            field=models.DateTimeField(null=True),
        ),
    ]
