# Generated by Django 4.2.2 on 2023-12-23 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_alter_details_dispatch_date_alter_details_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='Details_id',
        ),
        migrations.AddField(
            model_name='details',
            name='cart_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.cart'),
        ),
    ]
