# Generated by Django 4.2.2 on 2023-12-28 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_product_product_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_items',
            new_name='product_sub_category',
        ),
    ]
