# Generated by Django 4.2.2 on 2023-12-23 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0007_remove_cart_details_id_details_cart_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='details',
            name='dispatch_date',
        ),
        migrations.RemoveField(
            model_name='details',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='details',
            name='order_id',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('product_color', models.CharField(max_length=50)),
                ('product_size', models.CharField(max_length=50)),
                ('total', models.IntegerField(default=0)),
                ('order_id', models.CharField(max_length=20)),
                ('company_id', models.CharField(max_length=20)),
                ('dispatch_date', models.DateTimeField()),
                ('order_date', models.DateTimeField()),
                ('status', models.BooleanField(default=True)),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.buyer')),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.cart')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.product')),
            ],
        ),
        migrations.CreateModel(
            name='Cancel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('product_color', models.CharField(max_length=50)),
                ('product_size', models.CharField(max_length=50)),
                ('total', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.buyer')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.product')),
            ],
        ),
        migrations.CreateModel(
            name='Accept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('product_color', models.CharField(max_length=50)),
                ('product_size', models.CharField(max_length=50)),
                ('total', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.buyer')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.product')),
            ],
        ),
    ]
