# Generated by Django 4.2.2 on 2024-01-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0008_product_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='mobile_no',
            field=models.CharField(default='+ 91', max_length=10),
        ),
    ]
