# Generated by Django 4.2.2 on 2023-12-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0008_remove_details_company_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
        migrations.AddField(
            model_name='details',
            name='order_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
