# Generated by Django 4.2.2 on 2024-01-04 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0009_alter_register_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='mobile_no',
            field=models.CharField(default='+ 91', max_length=10, unique=True),
        ),
    ]
