# Generated by Django 4.2.2 on 2023-12-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0009_remove_order_order_id_details_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
