# Generated by Django 4.2.2 on 2024-01-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0010_alter_register_mobile_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_stock',
            field=models.CharField(default='Is Stock', max_length=20),
        ),
    ]
