# Generated by Django 4.2.2 on 2023-12-23 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0010_order_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accept',
            old_name='buyer_id',
            new_name='buyer',
        ),
        migrations.RenameField(
            model_name='accept',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='accept',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='cancel',
            old_name='buyer_id',
            new_name='buyer',
        ),
        migrations.RenameField(
            model_name='cancel',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='cancel',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='buyer_id',
            new_name='buyer',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='stetus',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='buyer_id',
            new_name='buyer',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='cart_id',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='buyer_id',
            new_name='buyer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='cart_id',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='company_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='product_id',
            new_name='product',
        ),
    ]
