# Generated by Django 4.2.5 on 2023-12-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0012_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
