from django.urls import path
from seller import views

urlpatterns = [
    path('', views.register),
    path('otp_verification/', views.otp_verification),
    path('login/', views.login),
    path('logout/', views.logout),
    path('profile/', views.profile),
    path('update_profile/', views.update_profile),
    path('add_product/', views.add_product),
    path('bulk_upload_catalog/', views.bulk_upload_catalog),
    path('get_image_link/', views.get_image_link),
    path('upload_catalog_file/', views.upload_catalog_file),
    path('view_all_product/', views.view_all_product),
    path('update_product/', views.update_product),
    path('delete_product/', views.delete_product),
    path('inventory/', views.inventory),
    path('edit_stock/', views.edit_stock),
    path('inventory_filter_category/', views.inventory_filter_category),
    path('inventory_edit_catalog/', views.inventory_edit_catalog),
    path('pending_order/', views.pending_order),
    path('filter_order_date/', views.filter_order_date),
    path('filter_dispatch_date/', views.filter_dispatch_date),
    path('order_search/', views.order_search),
    path('order_accept/', views.order_accept),
    path('ready_to_ship/', views.ready_to_ship),
    path('shipping_label/', views.shipping_label),
    path('cancel_order/', views.cancel_order),
    path('cancelled/', views.cancelled),
    path('pricing/', views.pricing),
    path('edit_pricing/', views.edit_pricing),
    path('filter_category/', views.filter_category),
    path('date_growth/', views.date_growth),
    path('return_tracking/', views.return_tracking),
    path('return_overview/', views.return_overview),
]
