# Generated by Django 4.2.5 on 2023-12-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_user_emailid_buyerregistration_user_email_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerregistration',
            name='user_photo',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
