# Generated by Django 4.2.5 on 2023-12-25 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_address_type_address_select_state'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='BuyerAddress',
        ),
    ]
