# Generated by Django 4.2.5 on 2023-12-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_address_buyeraddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyeraddress',
            name='id',
        ),
        migrations.AddField(
            model_name='buyeraddress',
            name='address_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
