# Generated by Django 4.2.5 on 2024-01-01 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyercart',
            name='product',
        ),
    ]
