# Generated by Django 4.2.5 on 2024-01-01 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
        ('buyer', '0003_remove_buyercart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyercart',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.product'),
        ),
    ]
